=== Bobcat66/wayfinder/jval/jval_schema.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "$id": "jval_schema.schema.json",
    "title": "JVal metaschema",
    "definitions": {
        "basicType": {
            "type": "string",
            "enum": [
                "integer",
                "number",
                "boolean",
                "string",
                "array",
                "enum",
                "struct",
                "map",
                "union",
                "pattern",
                "any"
            ]
        },
        "reference": {
            "description": "A reference to another schema in another file. The other schema file must be linked during compilation, and should be referenced by its $name",
            "type": "object",
            "properties": {
                "$ref": { "$ref": "#/definitions/schemaName" }
            },
            "required": ["$ref"],
            "additionalProperties": false
        },
        "subschema": {
            "oneOf": [
                { "$ref": "#" },
                { "$ref": "#/definitions/reference" }
            ]
        },
        "schemaName": {
            "description": "A valid name for a schema",
            "type": "string",
            "pattern": "^([A-Za-z])\\w*$"
        },
        "propertyName": {
            "description": "A valid name for a property",
            "$ref": "#/definitions/schemaName"
        },
        "propertySet": {
            "description": "A set of property names",
            "type": "array",
            "items": { "$ref" : "#/definitions/propertyName" },
            "uniqueItems": true,
            "default": []
        }
    },
    "properties": {
        "$schema": { "type": "string" },
        "$name": { "$ref": "#/definitions/schemaName" },
        "type": { "$ref": "#/definitions/basicType" },
        "properties": {
            "description": "Struct properties",
            "type": "object",
            "propertyNames": { "pattern": "^([A-Za-z])\\w*$" },
            "additionalProperties": { "$ref": "#/definitions/subschema" },
            "default": {}
        },
        "required": { 
            "description": "Required struct properties",
            "$ref": "#/definitions/propertySet"  
        },
        "dependencies": {
            "description": "Dependent struct property requirements",
            "type": "object",
            "propertyNames": { "pattern": "^([A-Za-z])\\w*$" },
            "additionalProperties": { "$ref": "#/definitions/propertySet" },
            "default": {}
        },
        "enumValues": {
            "description": "Enum values",
            "type": "array",
            "items": { "type": "string" },
            "uniqueItems": true,
            "default": []
        },
        "schemas": {
            "description": "possible schemas of a Union",
            "type": "array",
            "items": { "$ref": "#/definitions/subschema" },
            "default": []
        },
        "regex": {
            "description": "regex pattern to match against",
            "type": "string",
            "default": "(^.*$)"
        },
        "mapKeys": {
            "description": "regex pattern to match map keys against",
            "type": "string",
            "default": "(^.*$)"
        },
        "mapValues": {
            "description": "Schema to match map values against",
            "$ref": "#/definitions/subschema",
            "default": { "type": "any" }
        },
        "items": {
            "description": "Schema to match array values against",
            "$ref": "#/definitions/subschema",
            "default": { "type": "any" }
        },
        "minSize": {
            "description": "Minimum array size",
            "type": ["integer","boolean"],
            "default": false
        },
        "maxSize": {
            "description": "Maximum array size",
            "type": ["integer","boolean"],
            "default": false
        }
    },
    "required": ["type"],
    "dependencies": {
        "$schema": ["$name"]
    },
    "additionalProperties": false
}

=== Bobcat66/wayfinder/jval/schemas/camera_config.json
{
    "$schema": "../jval_schema.schema.json",
    "$name": "CameraConfig",
    "type": "struct",
    "properties": {
        "nickname": { "type": "string" },
        "devpath": { "type": "string" },
        "backend": { 
            "type": "enum",
            "enumValues": [
                "CSCORE",
                "REALSENSE",
                "GSTREAMER",
                "LIBCAMERA"
            ]
        },
        "format": { "$ref": "StreamFormat" },
        "controlAliases": {
            "type": "map",
            "mapKeys": "^(EXPOSURE|AUTO_EXPOSURE|BRIGHTNESS|ISO|SHUTTER|FOCUS|ZOOM|WHITE_BALANCE|AUTO_WHITE_BALANCE|SHARPNESS|SATURATION|CONTRAST|GAMMA|HUE)$",
            "mapValues": { "type": "string" }
        },
        "calibrations": {
            "type": "array",
            "items": { "$ref": "CameraIntrinsics" }
        },
        "controls": {
            "type": "map",
            "mapKeys": "^(EXPOSURE|AUTO_EXPOSURE|BRIGHTNESS|ISO|SHUTTER|FOCUS|ZOOM|WHITE_BALANCE|AUTO_WHITE_BALANCE|SHARPNESS|SATURATION|CONTRAST|GAMMA|HUE)$",
            "mapValues": { "type": "integer" }
        }
    },
    "required": [
        "nickname",
        "devpath",
        "backend",
        "format"
    ],
    "dependencies": {
        "controls": ["controlAliases"]
    }
}

=== Bobcat66/wayfinder/jval/schemas/wf_defaults.jval.json
{
    "$schema": "../jval_schema.schema.json",
    "$name": "WFDefaults",
    "type": "struct",
    "properties": {
        "engineType": { "$ref": "InferenceEngineType"},
        "modelArch": { "$ref": "ModelArchitecture"},
        "tensorParams": { "$ref": "TensorParams"},
        "nmsThreshold": { "type": "number" },
        "confidenceThreshold": { "type": "number" },
        "modelFile": { "type": "string" },
        "modelColorSpace": { "$ref": "ImageEncoding" },
        "qtps": { "$ref": "QuadThresholdParams"},
        "tagDetectorConfig": { "$ref": "ApriltagDetectorConfig" },
        "tagSize": { "type": "number" },
        "tagFamily": { "type": "string" },
        "tagField": { "type": "string" }
    },
    "required": [
        "engineType",
        "modelArch",
        "tensorParams",
        "nmsThreshold",
        "confidenceThreshold",
        "modelFile",
        "modelColorSpace",
        "qtps",
        "tagDetectorConfig",
        "tagSize",
        "tagFamily",
        "tagField"
    ]
}

=== Bobcat66/wayfinder/jval/schemas/camera_intrinsics.jval.json
{
    "$schema": "../jval_schema.schema.json",
    "$name": "CameraIntrinsics",
    "type": "struct",
    "properties": {
        "resolution": {
            "type": "struct",
            "properties": {
                "width": { "type": "integer" },
                "height": { "type": "integer" }
            },
            "required": ["width","height"]
        },
        "matrix": {
            "type": "struct",
            "properties": {
                "fx": { "type": "number" },
                "fy": { "type": "number" },
                "cx": { "type": "number" },
                "cy": { "type": "number" }
            },
            "required": ["fx","fy","cx","cy"]
        },
        "distortion": {
            "type": "array",
            "items": { "type": "number" },
            "minSize": 5,
            "maxSize": 8
        }
    },
    "required": [
        "resolution",
        "matrix",
        "distortion"
    ]
}

=== Bobcat66/wayfinder/jval/schemas/objdetect_pipeline_config.jval.json
{
    "$schema": "../jval_schema.schema.json",
    "$name": "ObjectDetectionPipelineConfig",
    "type": "struct",
    "properties": {
        "modelFile": { "type": "string" },
        "modelArch": { "$ref": "ModelArchitecture" },
        "engineType": { "$ref": "InferenceEngineType" },
        "tensorParams": { "$ref": "TensorParams" },
        "modelColorSpace": { "$ref": "ImageEncoding" },
        "filterParams": { "$ref": "FilteringParameters" }
    },
    "dependencies": {
        "modelFile": [
            "modelArch",
            "engineType",
            "tensorParams",
            "modelColorSpace"
        ]
    }
}

=== Bobcat66/wayfinder/jval/schemas/vision_worker_config.jval.json
{
    "$schema": "../jval_schema.schema.json",
    "$name": "VisionWorkerConfig",
    "type": "struct",
    "properties": {
        "camera_nickname": { "type": "string" },
        "name": { "type": "string" },
        "inputFormat": { "$ref": "FrameFormat" },
        "outputFormat": { "$ref": "StreamFormat" },
        "stream": { "type": "boolean" },
        "raw_port": { "type": "integer" },
        "processed_port": { "type": "integer" },
        "pipelineType": { 
            "type": "enum",
            "enumValues": [
                "Apriltag",
                "ObjDetect"
            ]
        },
        "pipelineConfig": {
            "type": "union",
            "schemas": [
                { "$ref": "ObjectDetectionPipelineConfig"},
                { "$ref": "ApriltagPipelineConfig"}
            ]
        }
    },
    "required": [
        "camera_nickname",
        "name",
        "stream",
        "pipelineType",
        "pipelineConfig"
    ]
}

=== Bobcat66/wayfinder/jval/schemas/quad_threshold_params.jval.json
{
    "$schema": "../jval_schema.schema.json",
    "$name": "QuadThresholdParams",
    "type": "struct",
    "properties": {
        "minClusterPixels": { "type": "integer" },
        "maxNumMaxima": { "type": "integer" },
        "criticalAngleRads": { "type": "number" },
        "maxLineFitMSE": { "type": "number" },
        "minWhiteBlackDiff": { "type": "integer" },
        "deglitch": { "type": "boolean" }
    },
    "required": [
        "minClusterPixels",
        "maxNumMaxima",
        "criticalAngleRads",
        "maxLineFitMSE",
        "minWhiteBlackDiff",
        "deglitch"
    ]
}

=== Bobcat66/wayfinder/jval/schemas/tensor_parameters.jval.json
{
    "$schema": "../jval_schema.schema.json",
    "$name": "TensorParams",
    "type": "struct",
    "properties": {
        "interleaved": { "type": "boolean" },
        "height": { "type": "integer" },
        "width": { "type": "integer" },
        "channels": { "type": "integer" },
        "scale": { "type": "number" },
        "stds": {
            "type": "array",
            "items": { "type": "number" },
            "minSize": 1,
            "maxSize": 4
        },
        "means": {
            "type": "array",
            "items": { "type": "number" },
            "minSize": 1,
            "maxSize": 4
        }
    },
    "required": [
        "interleaved",
        "height",
        "width",
        "channels",
        "scale",
        "stds",
        "means"
    ]
}

=== Bobcat66/wayfinder/jval/schemas/filtering_params.jval.json
{
    "$schema": "../jval_schema.schema.json",
    "$name": "FilteringParameters",
    "type": "struct",
    "properties": {
        "nmsThreshold": { "type": "number" },
        "confidenceThreshold": { "type": "number" }
    },
    "required": [
        "nmsThreshold",
        "confidenceThreshold"
    ]
}
