=== Bobcat66/wayfinder/schemas/wf_defaults.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "wf_defaults",
    "type": "object",
    "properties": {
        "engineType": { "$ref": "objdetect_pipeline_configuration.schema.json#/$defs/inference_engine_type"},
        "modelArch": { "$ref": "objdetect_pipeline_configuration.schema.json#/$defs/model_architecture"},
        "tensorParams": { "$ref": "objdetect_pipeline_configuration.schema.json#/$defs/tensor_parameters"},
        "nmsThreshold": { "type": "number" },
        "confidenceThreshold": { "type": "number" },
        "modelFile": { "type": "string" },
        "modelColorSpace": { "$ref": "frame_format.schema.json#/$defs/image_encoding" },
        "qtps": { "$ref": "apriltag_pipeline_configuration.schema.json#/$defs/quad_threshold_parameters"},
        "tagDetectorConfig": { "$ref": "apriltag_pipeline_configuration.schema.json#/$defs/apriltag_detector_config" },
        "tagSize": { "type": "number" },
        "tagFamily": { "type": "string" },
        "tagField": { "type": "string" }
    },
    "required": [
        "engineType",
        "modelArch",
        "tensorParams",
        "nmsThreshold",
        "confidenceThreshold",
        "modelFile",
        "modelColorSpace",
        "qtps",
        "tagDetectorConfig",
        "tagSize",
        "tagFamily",
        "tagField"
    ],
    "additionalProperties": false
}

=== Bobcat66/wayfinder/resources/defaults.json
{
    "engineType": "default",
    "modelArch": "YOLO",
    "tensorParams": {
        "interleaved": false,
        "height": 640,
        "width": 640,
        "channels": 3,
        "scale": 0.00392156862745098,
        "stds": [1.0, 1.0, 1.0],
        "means": [0.0, 0.0, 0.0]
    },
    "nmsThreshold": 0.5,
    "confidenceThreshold": 0.5,
    "modelFile": "model.onnx",
    "modelColorSpace": "RGB24",
    "qtps": {
        "minClusterPixels": 5,
        "maxNumMaxima": 10,
        "criticalAngleRads": 0.0,
        "maxLineFitMSE": 10.0,
        "minWhiteBlackDiff": 5,
        "deglitch": false
    },
    "tagDetectorConfig": {
        "numThreads": 1,
        "quadDecimate": 2.0,
        "quadSigma": 0.0,
        "refineEdges": true,
        "decodeSharpening": 0.25,
        "debug": false
    },
    "tagSize": 0.162,
    "tagFamily": "tag36h11",
    "tagField": "2025-reefscape-welded.json"
}
